# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.test                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: douzgane <douzgane@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/02/24 23:58:21 by douzgane          #+#    #+#              #
#    Updated: 2025/02/25 13:56:02 by douzgane         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = test_parser

CC = gcc
CFLAGS = -Wall -Wextra -Werror

INCLUDES = -I../../includes -I../../libft/inc
LIBS = -L../../libft -lft

OBJ_DIR = obj

SRCS = parser_core.c \
       parser_cmd.c \
       parser_memory.c \
       parser_utils.c \
       parser_args.c \
       ../lexer/lexer.c \
       ../lexer/char_utils.c \
       ../lexer/env_utils.c \
       ../lexer/error_utils.c \
       ../lexer/operator_utils.c \
       ../lexer/quote_utils.c \
       ../lexer/token_utils.c \
       ../lexer/word_utils.c \
       ../env/env_expand.c \
       ../env/env_expand_utils.c \
       ../env/env_core.c \
       ../env/env_utils.c \
       ../env/env_parser.c \
       parser_test.c

OBJS = $(addprefix $(OBJ_DIR)/, $(SRCS:.c=.o))

all: $(OBJ_DIR) $(NAME)

$(OBJ_DIR):
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(OBJ_DIR)/lexer
	@mkdir -p $(OBJ_DIR)/env

$(NAME): $(OBJS)
	$(CC) $(OBJS) $(LIBS) -o $(NAME)

$(OBJ_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -rf $(OBJ_DIR)

fclean: clean
	rm -f $(NAME)

re: fclean all

test: all
	./$(NAME)

.PHONY: all clean fclean re test
